### ISSUE TITLE
Access Paho.Message

### ISSUE THREAD

**Issue by kcdipesh** [skt-t1-byungi/rsup-mqtt#4]
I tried to set Last Will Message  as mentioned on the docs but is throwing some error. 

Upon deep diving, tt seems like current wrapper send option through the key  `will`.
![Screenshot from 2020-02-03 17-22-24](https://user-images.githubusercontent.com/596300/73650240-cbc00d80-46a9-11ea-971d-fff679101983.png)

 However paho mqtt expects option via `willMessage` key and hence the validate method throws an error)
![Screenshot from 2020-02-03 17-12-47](https://user-images.githubusercontent.com/596300/73649704-79cab800-46a8-11ea-8026-f9ccd9eeaf5e.png)

**Comment by skt-t1-byungi** [comment]
Thank you so much. I fixed this problem.
5f1ec2656c9dd6db0d5dae97ea30cab0e30b6981
